# Generated by Django 4.2.26 on 2025-11-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='snippets.editorial')),
            ],
        ),
        migrations.AlterField(
            model_name='opinion',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='snippets.book'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='snippets.book'),
        ),
        migrations.DeleteModel(
            name='libro',
        ),
    ]
