# Generated by Django 4.2.26 on 2025-11-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_book_alter_opinion_libro_alter_snippet_fuente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='libro',
            new_name='book',
        ),
    ]
