# Generated by Django 4.2.26 on 2025-11-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0003_rename_libro_opinion_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="autor",
            new_name="author",
        ),
    ]
