# Generated by Django 4.2.26 on 2025-12-30 08:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_company_remove_editorial_email_remove_editorial_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.region')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('municipality_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snippets.municipality')),
                ('population', models.IntegerField(validators=[django.core.validators.MinValueValidator(10000)])),
            ],
            bases=('snippets.municipality',),
        ),
        migrations.CreateModel(
            name='town',
            fields=[
                ('municipality_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='snippets.municipality')),
                ('population', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
            ],
            bases=('snippets.municipality',),
        ),
    ]
