# Generated by Django 4.2.26 on 2025-12-30 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_municipality_city_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='population',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
