# Generated by Django 4.2.26 on 2025-12-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_alter_town_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
