# Generated by Django 4.2.26 on 2025-12-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_alter_municipality_name_alter_region_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together={('name', 'region')},
        ),
    ]
