# Generated by Django 4.2.26 on 2026-01-29 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0017_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="snippet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="snippets.snippet",
            ),
            preserve_default=False,
        ),
    ]
