# Generated by Django 4.2.26 on 2026-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
